### ISSUE TITLE
The link does not appear in the browser

### ISSUE THREAD

**Issue by sonnysj** [jor3l/broadlinkrm-ifttt#15] opened 2018-04-05 04:03 UTC
Hi jor3l,

I have run index.js on the server, but after i open in browser just look like this.
Run the server with node index
![broadlink-server](https://user-images.githubusercontent.com/38024966/38346498-a7f0213c-38bf-11e8-964c-5c95889c3611.PNG)
Run link in browser:
![browser-firefox](https://user-images.githubusercontent.com/38024966/38346502-b0c17892-38bf-11e8-934c-4c6493cedd5c.PNG)
![browser-firefox-1](https://user-images.githubusercontent.com/38024966/38346651-bc59e01c-38c0-11e8-8d34-939c02407589.PNG)

There is something wrong?
There is a video successfully running this?

**Comment by jor3l** [comment] 2018-04-07 15:03
The problem is your node isn't finding the broadlink. Are they in the same network? Is it possible to try using another computer not running windows? I had some issues with finding the Broadlink with that OS before. Let me know

**Comment by jor3l** [comment] 2018-04-14 01:05
Let me know if is solved, thanks

**Comment by jor3l** [comment] 2018-04-29 18:14
I'm closing, reopen if need help

**Closed by jor3l** 2018-04-29 18:14 UTC

**Comment by jeffl78** [comment] 2018-05-26 01:51
I am having the same issue on my raspberry pi 3b running Raspbian.
